import {readFileSync} from 'node:fs';
import {test,after} from 'node:test';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db=new PGlite();
await db.exec(readFileSync(new URL('./free-flow-fixture.sql',import.meta.url),'utf8'));
const migration=readFileSync(new URL('../../supabase/migrations/20261002070000_free_flow_atomic_guard.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration); // idempotent additive deploy
const h=x=>x.repeat(64),sid='00000000-0000-0000-0000-000000000001';
const ip=h('a'),fp=h('b'),ua=h('c'),out=h('d'),gate=h('e'),out2=h('f'),claim=h('1'),gate2=h('2');
async function reset({double=false,early=false,expired=false,gtraffic=false}={}){
 await db.exec('UPDATE licenses_free_settings SET free_enabled=true,free_secondary_enabled=true');
 await db.exec('TRUNCATE licenses_free_sessions,licenses_free_gate_tokens,licenses_free_issues,licenses_free_shortlink_providers,licenses_free_blocklist');
 await db.query(`INSERT INTO licenses_free_sessions(session_id,out_token_hash,expires_at,out_expires_at,fingerprint_hash,ip_hash,ua_hash,passes_required,gate_flow_version) VALUES($1,$2,clock_timestamp()+interval '20 minutes',clock_timestamp()+interval '20 minutes',$3,$4,$5,$6,'tokenized_v1')`,[sid,out,fp,ip,ua,double?2:1]);
 if(gtraffic)await db.query("INSERT INTO licenses_free_shortlink_providers VALUES($1,'gtraffic')",[sid]);
 await db.query(`INSERT INTO licenses_free_gate_tokens(session_id,pass_no,token_hash,status,activate_after_at,expires_at,fingerprint_hash,ip_hash,ua_hash,provider_id) VALUES($1,1,$2,'pending',clock_timestamp()+$3::interval,clock_timestamp()+$4::interval,$5,$6,$7,$8)`,[sid,gate,early?'30 seconds':'-30 seconds',expired?'-1 second':'10 minutes',fp,ip,ua,gtraffic?sid:null]);
}
async function rpc(name,values){const q=await db.query(`SELECT ${name}(${values.map((_,i)=>'$'+(i+1)).join(',')}) AS r`,values);return q.rows[0].r}
const consume=(overrides={})=>rpc('free_flow_consume_gate',Object.values({gate,out,fp,ip,ua,sid,pass:1,next:out2,claim,window:180,...overrides}));
const publish=(pass=2,o=out2,g=gate2)=>rpc('free_flow_publish_gate',[pass,sid,o,g,'https://short.test/opaque',null,0,600,'primary']);
const begin=(overrides={})=>rpc('free_flow_begin_claim',Object.values({claim,out,fp,ip,ua,sid,fpLimit:0,ipLimit:0,...overrides}));
const session=async()=> (await db.query('SELECT * FROM licenses_free_sessions')).rows[0];
async function burned(){const s=await session();assert.equal(s.status,'closed');for(const k of ['out_token_hash','out_token_hash_pass2','claim_token_hash'])assert.equal(s[k],null);assert.equal((await db.query("SELECT count(*)::int n FROM licenses_free_gate_tokens WHERE status='pending'")).rows[0].n,0)}

test('one-pass: gate and claim each authorize once',async()=>{await reset();assert.equal((await consume()).next,'CLAIM');assert.equal((await begin()).ok,true);assert.equal((await begin()).code,'REVEAL_IN_PROGRESS');});
test('two-pass rotates out token; pass1 secret cannot authorize pass2',async()=>{await reset({double:true});assert.equal((await consume()).next,'PASS2');assert.equal((await session()).out_token_hash,null);assert.equal((await publish()).ok,true);assert.equal((await consume({gate:gate2,pass:2})).code,'OUT_TOKEN_MISMATCH');assert.equal((await consume({gate:gate2,out:out2,pass:2})).next,'CLAIM');assert.equal((await begin({out:out2})).ok,true)});
test('claim cannot issue halfway through two-pass',async()=>{await reset({double:true});await consume();assert.equal((await begin({out:out2})).ok,false);assert.equal((await session()).reveal_count,0)});
for(const [name,opts,overrides,code] of [

 ['expired gate burns all tokens',{expired:true},{},'GATE_TOKEN_EXPIRED'],
 ['missing fingerprint burns authenticated pair',{}, {fp:''},'DEVICE_MISMATCH'],
 ['changed fingerprint burns authenticated pair',{}, {fp:h('3')},'DEVICE_MISMATCH'],
 ['changed IP burns authenticated pair',{}, {ip:h('3')},'IP_MISMATCH'],
 ['changed UA burns authenticated pair',{}, {ua:h('3')},'UA_MISMATCH'],
 ['spoofed pass fails',{}, {pass:2},'GATE_PASS_INVALID'],
 ['wrong session fails',{}, {sid:'other'},'SESSION_MISMATCH'],
])test(name,async()=>{await reset(opts);assert.equal((await consume(overrides)).code,code);await burned()});
test('wrong token or guessed session cannot close victim session',async()=>{await reset();assert.equal((await consume({out:h('3')})).code,'OUT_TOKEN_MISMATCH');assert.equal((await session()).status,'waiting');assert.equal((await consume({gate:h('4')})).code,'GATE_TOKEN_INVALID')});
for (const provider of ['gtraffic','link4m','other']) test(`${provider} early return replaces same pass; old pair cannot authorize`,async()=>{await reset({early:true,gtraffic:true});await db.query('UPDATE licenses_free_shortlink_providers SET provider=$1',[provider]);const r=await consume();assert.equal(r.next,'SHORTLINK_FALLBACK');assert.equal((await session()).passes_completed,0);assert.equal((await publish(1)).ok,true);assert.equal((await consume()).ok,false);assert.equal((await consume({gate:gate2,out:out2})).next,'CLAIM');assert.equal((await begin({out:out2})).ok,true)});
test('invalid binding on GTraffic never rotates',async()=>{await reset({early:true,gtraffic:true});assert.equal((await consume({ip:h('3')})).code,'IP_MISMATCH');await burned()});
test('duplicate gate requests create only one transition',async()=>{await reset({double:true});const r=await Promise.all([consume(),consume(),consume()]);assert.equal(r.filter(x=>x.ok).length,1);assert.equal((await publish()).ok,true);assert.equal((await publish()).ok,false)});
test('pass2 cannot publish into closed session',async()=>{await reset({double:true});await consume();await rpc('free_flow_burn',[sid,'TEST']);assert.equal((await publish()).ok,false)});
test('invalid pass1 evidence blocks final claim',async()=>{await reset({double:true});await consume();await publish();await consume({gate:gate2,out:out2,pass:2});await db.query("UPDATE licenses_free_gate_tokens SET used_at=activate_after_at-interval '1 second' WHERE pass_no=1");assert.equal((await begin({out:out2})).code,'GATE_CHAIN_INVALID');await burned()});
test('expired claim burns pair and prevents later reuse',async()=>{await reset();await consume();await db.query("UPDATE licenses_free_sessions SET claim_expires_at=clock_timestamp()-interval '1 second'");assert.equal((await begin()).code,'CLAIM_EXPIRED');await burned();assert.equal((await begin()).ok,false)});
test('claim binding is mandatory; changing IP cannot issue',async()=>{await reset();await consume();assert.equal((await begin({ip:h('3')})).code,'IP_MISMATCH');await burned()});
test('TTL cleanup revokes expired bearers',async()=>{await reset({expired:true});assert.equal(await rpc('free_flow_expire',[]),1);await burned()});
test('in-flight claim reserves daily quota across sessions',async()=>{await reset();await consume();assert.equal((await begin({fpLimit:1})).ok,true);await db.query(`INSERT INTO licenses_free_sessions(session_id,status,closed_at,out_token_hash,out_token_hash_pass2,claim_token_hash,expires_at,out_expires_at,claim_expires_at,fingerprint_hash,ip_hash,ua_hash,passes_required,passes_completed,current_pass,gate_flow_version,pass1_ok_at,pass2_ok_at,gate_ok_at,last_error,reveal_count,revealed_at,app_code,selection_meta,started_at,key_type_code,duration_seconds,trace_id,gate_token_life_seconds,provider_id_pass1,provider_id_pass2,shortlink_channel,package_code,credit_code,wallet_kind,revealed_license_id,close_deadline_at,copied_at,issued_server_redeem_key_id,issued_server_reward_mode) SELECT '00000000-0000-0000-0000-000000000002'::uuid,status,closed_at,out_token_hash,out_token_hash_pass2,$1,expires_at,out_expires_at,claim_expires_at,fingerprint_hash,ip_hash,ua_hash,passes_required,passes_completed,current_pass,gate_flow_version,pass1_ok_at,pass2_ok_at,gate_ok_at,last_error,reveal_count,revealed_at,app_code,selection_meta,started_at,key_type_code,duration_seconds,trace_id,gate_token_life_seconds,provider_id_pass1,provider_id_pass2,shortlink_channel,package_code,credit_code,wallet_kind,revealed_license_id,close_deadline_at,copied_at,issued_server_redeem_key_id,issued_server_reward_mode FROM licenses_free_sessions`,[h('3')]);await db.query("UPDATE licenses_free_sessions SET status='gate_ok',reveal_count=0,revealed_at=NULL WHERE session_id<>$1",[sid]);await db.query("INSERT INTO licenses_free_gate_tokens(session_id,pass_no,token_hash,status,activate_after_at,expires_at,used_at,fingerprint_hash,ip_hash,ua_hash) SELECT '00000000-0000-0000-0000-000000000002'::uuid,pass_no,$1,status,activate_after_at,expires_at,used_at,fingerprint_hash,ip_hash,ua_hash FROM licenses_free_gate_tokens",[h('4')]);const r=await begin({claim:h('3'),sid:'00000000-0000-0000-0000-000000000002',fpLimit:1});assert.equal(r.code,'RATE_LIMIT')});
test('pass2 early arrival rotates without completion and old pair fails',async()=>{await reset({double:true});await consume();await publish();await db.query("UPDATE licenses_free_gate_tokens SET activate_after_at=clock_timestamp()+interval '30 seconds' WHERE pass_no=2");const next=h('5');assert.equal((await consume({gate:gate2,out:out2,pass:2,next})).next,'SHORTLINK_FALLBACK');assert.equal((await session()).passes_completed,1);assert.equal((await consume({gate:gate2,out:out2,pass:2,next})).ok,false);assert.equal((await begin({out:next})).ok,false)});
test('pass2 GTraffic replacement preserves pass1 proof',async()=>{await reset({double:true});await consume();await publish();await db.query("INSERT INTO licenses_free_shortlink_providers VALUES($1,'gtraffic')",[sid]);await db.query("UPDATE licenses_free_gate_tokens SET provider_id=$1,activate_after_at=clock_timestamp()+interval '30 seconds' WHERE pass_no=2",[sid]);const next=h('5'),newGate=h('6');assert.equal((await consume({gate:gate2,out:out2,pass:2,next})).next,'SHORTLINK_FALLBACK');assert.equal((await session()).passes_completed,1);assert.equal((await publish(2,next,newGate)).ok,true);assert.equal((await consume({gate:newGate,out:next,pass:2})).next,'CLAIM');assert.equal((await begin({out:next})).ok,true)});
test('forged completion counters without gate evidence never authorize claim',async()=>{await reset();await db.query("UPDATE licenses_free_sessions SET status='gate_ok',passes_completed=1,gate_ok_at=clock_timestamp(),claim_token_hash=$1,claim_expires_at=clock_timestamp()+interval '3 minutes'",[claim]);assert.equal((await begin()).code,'GATE_CHAIN_INVALID');await burned()});
test('blocked identity cannot complete gate',async()=>{await reset();await db.query("INSERT INTO licenses_free_blocklist(enabled,fingerprint_hash) VALUES(true,$1)",[fp]);assert.equal((await consume()).code,'BLOCKED');await burned()});
test('rotation bound prevents endless exhausted-provider loops',async()=>{await reset({early:true,gtraffic:true});await db.query(`UPDATE licenses_free_sessions SET selection_meta='{"free_rotation_count":3}'`);assert.equal((await consume()).code,'SHORTLINK_ROTATION_LIMIT');await burned()});
const finish=async()=>{await db.exec("INSERT INTO licenses(id,key) VALUES('30000000-0000-0000-0000-000000000001','fixture-key') ON CONFLICT DO NOTHING");return rpc('free_flow_finish_claim',[sid,'30000000-0000-0000-0000-000000000001','SUNNY-****',new Date(Date.now()+3600000).toISOString(),'free-fire','FF',null,null,60]);};
test('finish records one issue and atomically revokes all tokens',async()=>{await reset();await consume();await begin();assert.equal((await finish()).ok,true);const s=await session();assert.equal(s.status,'revealed');assert.equal(s.out_token_hash,null);assert.equal(s.claim_token_hash,null);assert.equal((await db.query('SELECT count(*)::int n FROM licenses_free_issues')).rows[0].n,1);assert.equal((await finish()).ok,false);assert.equal((await begin()).ok,false)});
test('audit write failure never reports finalized issuance',async()=>{await reset();await consume();await begin();await db.exec("ALTER TABLE licenses_free_issues ADD CONSTRAINT fixture_failure CHECK(false)");await assert.rejects(finish,/fixture_failure/);assert.equal((await session()).status,'revealing');assert.equal((await begin()).code,'REVEAL_IN_PROGRESS');await db.exec("ALTER TABLE licenses_free_issues DROP CONSTRAINT fixture_failure")});
test('AI issuance uses its own foreign key instead of the Find Dumps table',async()=>{await reset();await db.query("UPDATE licenses_free_sessions SET app_code='ai-coding'");await consume();await begin();await db.query("INSERT INTO ai_sunny_redeem_keys VALUES($1)",[sid]);const r=await rpc('free_flow_finish_claim',[sid,null,'AI-****',new Date(Date.now()+3600000).toISOString(),'ai-coding','AI-SUNNY',sid,'ai_redeem',60]);assert.equal(r.ok,true);assert.equal((await session()).issued_server_redeem_key_id,null);assert.equal((await session()).issued_ai_redeem_key_id,sid);const issue=(await db.query('SELECT * FROM licenses_free_issues')).rows[0];assert.equal(issue.server_redeem_key_id,null);assert.equal(issue.ai_redeem_key_id,sid)});
test('feature disabled during a session cannot issue a claim',async()=>{await reset();await db.exec('UPDATE licenses_free_settings SET free_enabled=false');assert.equal((await consume()).code,'FREE_DISABLED');await burned()});
test('anon/authenticated cannot call authorization RPCs',async()=>{for(const role of ['anon','authenticated']){await db.exec('SET ROLE '+role);await assert.rejects(()=>consume(),/permission denied/);await assert.rejects(()=>rpc('free_flow_burn',[sid,'TEST']),/permission denied/);await db.exec('RESET ROLE')}});
after(()=>db.close());
