import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {ModeratorKeyDialog} from '@/features/moderator/ModeratorKeyDialog';
import {KeyInformation} from '@/features/licenses/KeyInformation';
const m=vi.hoisted(()=>({calls:[] as any[],fail:false,info:{key_hint:'SUNNY-AAAA-BBBB-CCCC',remaining_seconds:600,max_devices:2,device_count:1,devices:[{name:'Samsung Galaxy S24',identity:'device-01',first_seen:'2026-10-03'}],status:'not_started',admin_reset_count:1,public_reset_count:0,note:'Test',version:{expires_at:null,duration_seconds:'600',max_devices:'2',resets:1},ledger:[]}}));
vi.mock('@/hooks/use-panel-role',()=>({usePanelRole:()=>({userId:'mod'})}));
vi.mock('@/features/moderator/wallet-api',()=>({walletRpc:async(name:string,args:any)=>{if(name==='moderator_key_details')return m.info;m.calls.push({name,args});if(m.fail){m.fail=false;throw Error('Network interrupted');}return {ok:true,amount:-10};}}));
function mount(edit=false){render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><ModeratorKeyDialog row={{engine:'sunny',license_id:'key'}} edit={edit} onClose={()=>{}}/></QueryClientProvider>);}
beforeEach(()=>{m.calls=[];m.fail=false;vi.spyOn(window,'confirm').mockReturnValue(true);Object.defineProperty(crypto,'randomUUID',{configurable:true,value:()=> 'fixed-request'});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
it('public information shows countdown, server reset allowance and next penalty',()=>{render(<KeyInformation data={{remaining_seconds:90000,status:'not_started',device_count:1,max_devices:2,total_reset_count:3,public_reset_count:2,admin_reset_count:1,reset_limit:5,resets_remaining:3,next_reset_penalty_pct:20,next_remaining_seconds:72000}}/>);expect(screen.getByText('1 ngày 1 giờ 0 phút')).toBeTruthy();expect(screen.getByText('Còn 3 lượt reset theo chính sách')).toBeTruthy();expect(screen.getByText(/Trừ 20%/)).toBeTruthy();});
it('Moderator info shows SUNNY device_name and has no device deletion control',async()=>{mount();await screen.findByText('Samsung Galaxy S24');expect(screen.queryByRole('button',{name:/Xóa|Reset|Gia hạn/})).toBeNull();expect(screen.getByText('device-01')).toBeTruthy();});
it('edit converts units and submits version and delta',async()=>{mount(true);const input=await screen.findByLabelText('Thêm / bớt thời gian · số âm để giảm');fireEvent.change(input,{target:{value:'60'}});fireEvent.change(screen.getByRole('combobox'),{target:{value:'hours'}});expect((input as HTMLInputElement).value).toBe('1');fireEvent.click(screen.getByRole('button',{name:'Lưu chỉnh sửa'}));await waitFor(()=>expect(m.calls).toHaveLength(1));expect(m.calls[0].args.p_data).toMatchObject({delta_minutes:60,max_devices:2,version:m.info.version});});
it('edit retains request on uncertain network failure and resubmits exact payload',async()=>{mount(true);await screen.findByLabelText('Số thiết bị tối đa');m.fail=true;fireEvent.click(screen.getByRole('button',{name:'Lưu chỉnh sửa'}));await screen.findByRole('button',{name:'Thử lại cùng giao dịch'});fireEvent.click(screen.getByRole('button',{name:'Thử lại cùng giao dịch'}));await waitFor(()=>expect(m.calls).toHaveLength(2));expect(m.calls[0]).toEqual(m.calls[1]);});
