import {Licenses2Page} from '@/pages/Licenses2';
vi.mock('@/hooks/use-panel-role',()=>({usePanelRole:()=>({role:'moderator',userId:'fixture-mod'})}));
import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import {cleanup,render,screen,fireEvent,waitFor} from '@testing-library/react';
import {MemoryRouter,Routes,Route,useLocation} from 'react-router-dom';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {ModeratorLicenses} from '@/features/moderator/ModeratorLicenses';
import {AdminModeratorWallet} from '@/features/moderator/AdminModeratorWallet';
import {convertDuration,durationSeconds} from '@/features/licenses/duration-units';
const m=vi.hoisted(()=>({calls:[] as any[],fail:false,raw:'SUNNY-AAAA-BBBB-CCCC'}));
vi.mock('@/features/moderator/wallet-api',()=>({walletBalance:async()=>100000,walletRpc:async(name:string,args:any)=>{m.calls.push({name,args});if(m.fail){m.fail=false;throw Error('network interrupted');}if(name==='moderator_keys_view')return [{id:'purchase',engine:'sunny',license_id:'license',key_hint:m.raw,cost:60,devices:1,total_reset_count:0}];if(name==='moderator_wallet_admin')return {email:'mod@example.com',balance:100,keys:1,ledger:[]};return {amount:-60,id:'key',balance:99940};}}));
vi.mock('@/features/licenses/licenses-api',()=>({generateLicenseKey:async()=>m.raw}));
vi.mock('@/features/customs/customs-api',()=>({customsDb:{from:()=>{const q:any={};for(const k of ['select','eq','order'])q[k]=()=>q;return q;}},customsChecked:async()=>[{signature:'TOOLA',name:'Tool'}],customsKey:async()=>({raw:'TOOLA-'+'A'.repeat(32),hash:'a'.repeat(64),hint:'TOOLA-…AAAAAA'})}));
function mount(ui:any){return render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter>{ui}</MemoryRouter></QueryClientProvider>);}
beforeEach(()=>{m.calls=[];m.fail=false;vi.spyOn(window,'confirm').mockReturnValue(true);let n=0;Object.defineProperty(crypto,'randomUUID',{configurable:true,value:()=>`request-${++n}`});});afterEach(()=>{cleanup();vi.restoreAllMocks();});
it.each([['minutes','hours',120,2],['hours','days',24,1],['days','minutes',2,2880],['minutes','days',1,1/1440]])('unit %s to %s keeps duration',(from,to,value,out)=>{expect(convertDuration(value,from as any,to as any)).toBe(out);expect(durationSeconds(out,to as any)).toBe(durationSeconds(value,from as any));});
it('moderator has create form without license list, renew or reset controls',async()=>{mount(<ModeratorLicenses mode="create"/>);await screen.findByText('Tool · TOOLA');expect(screen.queryByText('Actions')).toBeNull();expect(screen.queryByText('Gia hạn')).toBeNull();const selects=screen.getAllByRole('combobox');fireEvent.change(selects[2],{target:{value:'hours'}});expect((screen.getAllByRole('spinbutton')[0] as HTMLInputElement).value).toBe('1');fireEvent.change(selects[2],{target:{value:'days'}});expect(Number((screen.getAllByRole('spinbutton')[0] as HTMLInputElement).value)).toBeCloseTo(1/24);});
it('create computes minute x devices server request and uses selected activation type',async()=>{mount(<ModeratorLicenses mode="create"/>);await screen.findByText('Tool · TOOLA');fireEvent.change(screen.getAllByRole('spinbutton')[1],{target:{value:'2'}});fireEvent.change(screen.getAllByRole('combobox')[1],{target:{value:'fixed'}});fireEvent.click(screen.getByRole('button',{name:'Tạo key'}));await screen.findByText(m.raw);expect(m.calls[0].args.p_data).toMatchObject({engine:'sunny',duration_seconds:3600,max_devices:2,license_type:'fixed'});});
it('network failure retains request ID and raw key on create retry',async()=>{mount(<ModeratorLicenses mode="create"/>);await screen.findByText('Tool · TOOLA');m.fail=true;fireEvent.click(screen.getByRole('button',{name:'Tạo key'}));await screen.findByRole('button',{name:'Thử lại giao dịch tạo key'});fireEvent.click(screen.getByRole('button',{name:'Thử lại giao dịch tạo key'}));await screen.findByText(m.raw);expect(m.calls).toHaveLength(2);expect(m.calls[0].args).toEqual(m.calls[1].args);});
it('admin adjustments require email, signed integer amount and reason',async()=>{mount(<AdminModeratorWallet/>);fireEvent.change(screen.getByRole('textbox',{name:'Email Moderator'}),{target:{value:'mod@example.com'}});fireEvent.change(screen.getByRole('spinbutton'),{target:{value:'-20'}});fireEvent.change(screen.getByRole('textbox',{name:'Lý do'}),{target:{value:'Correction'}});fireEvent.click(screen.getByRole('button',{name:'Cộng / Trừ Xu'}));await waitFor(()=>expect(m.calls).toHaveLength(1));expect(m.calls[0].args).toMatchObject({p_email:'mod@example.com',p_amount:'-20',p_reason:'Correction'});});

it.each([['/licenses2?customs=TOOLA',false,'/licenses?customs=TOOLA'],['/licenses2/new?customs=TOOLA',true,'/licenses/new?customs=TOOLA&timing=first_use']])('legacy route redirects %s',(path,create,out)=>{function Destination(){const l=useLocation();return <p>{l.pathname+l.search}</p>;}render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/licenses2" element={<Licenses2Page/>}/><Route path="/licenses2/new" element={<Licenses2Page create/>}/><Route path="/licenses" element={<Destination/>}/><Route path="/licenses/new" element={<Destination/>}/></Routes></MemoryRouter>);expect(screen.getByText(out)).toBeTruthy();});

it('trash requests a separate server-filtered page without create or history controls',async()=>{mount(<ModeratorLicenses mode="trash"/>);await screen.findByText(m.raw);expect(m.calls[0]).toEqual({name:'moderator_keys_view',args:{p_page:0,p_trash:true}});expect(screen.getByRole('button',{name:'Actions'})).toBeTruthy();expect(screen.queryByText('Tạo key')).toBeNull();expect(screen.queryByText('Lịch sử Xu')).toBeNull();});
it('list requests live keys separately from trash',async()=>{mount(<ModeratorLicenses/>);await screen.findByText(m.raw);expect(m.calls[0]).toEqual({name:'moderator_keys_view',args:{p_page:0,p_trash:false}});});
