[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-store, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
