import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {CustomsStyles} from '@/features/customs/CustomsStyles';
import {walletRpc} from './wallet-api';
export function AdminModeratorWallet(){const [email,setEmail]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[info,setInfo]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[pending,setPending]=useState<any>(null),[page,setPage]=useState(0);
 async function run(adjust=false){if(busy)return;if(adjust&&!pending&&!window.confirm('Điều chỉnh '+amount+' Xu cho '+email+'?'))return;setBusy(true);setError('');try{let args=pending;if(!adjust)args={p_email:email};else if(!args){if(!Number.isSafeInteger(Number(amount))||Number(amount)===0)throw new Error('Nhập số Xu nguyên khác 0.');args={p_email:email,p_amount:amount,p_reason:reason,p_request:crypto.randomUUID()};setPending(args);}setInfo(await walletRpc('moderator_wallet_admin',args));setPage(0);if(adjust){setPending(null);setAmount('');setReason('');}}catch(e){if((e as any)?.rejected)setPending(null);setError(e instanceof Error?e.message:'Thao tác thất bại');}finally{setBusy(false);}}
 async function paginate(next:number){setBusy(true);setError('');try{const ledger=await walletRpc('moderator_ledger_page',{p_page:next,p_email:info.email});setInfo({...info,ledger});setPage(next);}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <section className="customs-workspace"><CustomsStyles/><h1 className="text-2xl font-semibold">Moderator · Xu</h1><div className="customs-card"><label>Email Moderator<Input disabled={busy||!!pending} type="email" value={email} onChange={e=>{setEmail(e.target.value);setInfo(null);}}/></label><Button variant="outline" disabled={busy||!!pending} onClick={()=>run()}>Xem thông tin</Button><label>Số Xu · số âm để trừ<Input disabled={busy||!!pending} type="number" step="1" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Lý do<Input disabled={busy||!!pending} value={reason} onChange={e=>setReason(e.target.value)}/></label><Button disabled={busy} onClick={()=>run(true)}>{pending?'Thử lại cùng giao dịch':'Cộng / Trừ Xu'}</Button>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</div>{info&&<div className="customs-card"><h2>{info.email}</h2><p className="text-xl font-semibold">{Number(info.balance).toLocaleString('vi-VN')} Xu</p><p>{info.keys} key chưa hoàn</p><h3>Lịch sử giao dịch gần đây</h3>{info.ledger?.map((r:any,i:number)=><div key={i} className="customs-row"><span>{new Date(r.created_at).toLocaleString()} · {r.kind}</span><strong className={r.amount<0?'text-red-700':'text-green-700'}>{r.amount>0?'+':''}{r.amount} Xu</strong><p className="text-xs">Số dư sau: {r.balance_after} · {r.detail?.reason||''}</p></div>)}<div className="customs-actions"><Button variant="outline" disabled={!page||busy} onClick={()=>paginate(page-1)}>Trước</Button><span>Trang {page+1}</span><Button variant="outline" disabled={busy||info.ledger?.length!==50} onClick={()=>paginate(page+1)}>Sau</Button></div><p className="text-xs">50 giao dịch mỗi trang. Sổ Xu được giữ để đối soát.</p></div>}</section>;
}
