import './moderator-key-dialog.css';
import {KeyRound,SlidersHorizontal,Smartphone} from 'lucide-react';
import {useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {KeyInformation,keyDuration} from '@/features/licenses/KeyInformation';
import {DurationUnit,convertDuration,durationSeconds} from '@/features/licenses/duration-units';
import {walletRpc} from './wallet-api';
import {usePanelRole} from '@/hooks/use-panel-role';
export function ModeratorKeyDialog({row,edit=false,onClose}:{row:any;edit?:boolean;onClose:()=>void}){const {userId}=usePanelRole(),qc=useQueryClient();const q=useQuery({queryKey:['moderator-details',userId,row.engine,row.license_id],queryFn:()=>walletRpc('moderator_key_details',{p_engine:row.engine,p_id:row.license_id})});return <Dialog open onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="moderator-key-dialog max-h-[90dvh] overflow-y-auto" aria-describedby={undefined}><DialogHeader><DialogTitle className="flex items-center gap-3"><span className="key-dialog-icon">{edit?<SlidersHorizontal size={20}/>:<KeyRound size={20}/>}</span>{edit?'Chỉnh sửa key':'Thông tin key'}</DialogTitle></DialogHeader><section className="customs-workspace">{q.isLoading?<p>Đang tải…</p>:q.error?<p role="alert">Không tải được thông tin: {String(q.error)}</p>:q.data&&<><p className="key-dialog-code break-all font-mono">{q.data.key_hint}</p><KeyInformation moderator data={q.data}/>{edit?<Editor key={JSON.stringify(q.data.version)} data={q.data} row={row} onDone={async()=>{await Promise.all(['moderator-details','moderator-keys','moderator-balance','moderator-ledger'].map(k=>qc.invalidateQueries({queryKey:[k]})));}}/>:<><p className="break-words">Ghi chú: {q.data.note||'—'}</p><h3 className="flex items-center gap-2"><Smartphone size={18}/>Thiết bị đăng nhập <span className="key-dialog-tag">Chỉ xem</span></h3>{q.data.devices?.length?q.data.devices.map((d:any,i:number)=><div key={i} className="customs-row"><strong>{d.name||'Chưa có tên thiết bị'}</strong><code className="break-all text-xs">{d.identity||'Chưa có mã'}</code><p className="text-xs">Lần đầu: {d.first_seen?new Date(d.first_seen).toLocaleString('vi-VN'):'—'}</p><p className="text-xs">Gần nhất: {d.last_seen?new Date(d.last_seen).toLocaleString('vi-VN'):'—'}</p></div>):<p>Chưa có thiết bị.</p>}<details><summary>Lịch sử giao dịch của key</summary>{q.data.ledger?.map((l:any,i:number)=><p key={i}>{new Date(l.created_at).toLocaleString('vi-VN')} · {l.kind} · {l.amount} Xu</p>)}</details></>}</>}</section></DialogContent></Dialog>;}
function Editor({data:d,row,onDone}:{data:any;row:any;onDone:()=>Promise<void>}){const [value,setValue]=useState('0'),[unit,setUnit]=useState<DurationUnit>('minutes'),[dev,setDev]=useState(String(d.max_devices)),[note,setNote]=useState(d.note||''),[pending,setPending]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState('');const delta=durationSeconds(Number(value),unit)/60,next=Number(d.remaining_seconds)+delta*60,difference=(next*Number(dev)-Number(d.remaining_seconds)*Number(d.max_devices))/60,charge=difference>=0?Math.ceil(difference):-Math.floor(-difference);async function save(){if(busy)return;setBusy(true);setError('');try{if(!Number.isSafeInteger(delta)||!Number.isInteger(Number(dev)))throw Error('Thay đổi thời gian phải là số phút nguyên.');if(!pending&&!window.confirm('Lưu chỉnh sửa và áp dụng chênh lệch Xu theo thời gian còn lại tại server?'))return;const request=pending||{id:crypto.randomUUID(),data:{engine:row.engine,id:row.license_id,delta_minutes:delta,max_devices:Number(dev),note,version:d.version}};setPending(request);const r=await walletRpc('moderator_key_edit',{p_request:request.id,p_data:request.data});setPending(null);setDone(Number(r.amount)>0?'Đã hoàn '+r.amount+' Xu':Number(r.amount)<0?'Đã trừ '+(-r.amount)+' Xu':'Đã lưu');setValue('0');await onDone();}catch(e){if((e as any)?.rejected)setPending(null);setError(String((e as any)?.message||e));}finally{setBusy(false);}}return <div className="customs-card"><label>Thêm / bớt thời gian · số âm để giảm<Input disabled={busy||!!pending} type="number" step="any" value={value} onChange={e=>setValue(e.target.value)}/><select disabled={busy||!!pending} value={unit} onChange={e=>{const u=e.target.value as DurationUnit;setValue(String(convertDuration(Number(value),unit,u)));setUnit(u);}}><option value="minutes">Phút</option><option value="hours">Giờ</option><option value="days">Ngày</option></select></label><label>Số thiết bị tối đa<Input disabled={busy||!!pending} type="number" min={Math.max(1,d.device_count)} max={20} value={dev} onChange={e=>setDev(e.target.value)}/></label><label>Ghi chú<Input disabled={busy||!!pending} value={note} onChange={e=>setNote(e.target.value)}/></label><p>Còn sau chỉnh sửa: {keyDuration(next)}</p><p className="key-edit-price">Dự kiến {charge>=0?'trừ':'hoàn'} {Math.abs(charge).toLocaleString('vi-VN')} Xu.</p><p className="text-xs text-muted-foreground">Server tính theo thời gian còn lại khi lưu: trừ Xu làm tròn lên, hoàn Xu làm tròn xuống. Không xóa thiết bị, không đổi kiểu kích hoạt hay lượt reset. Giảm giới hạn không được thấp hơn số máy đang gắn.</p>{error&&<p role="alert" className="text-destructive">{error}</p>}{done&&<p role="status">{done}</p>}<Button disabled={busy||!Number.isSafeInteger(delta)||next<60||Number(dev)<Math.max(1,d.device_count)||Number(dev)>20||['refunded','deleted','blocked'].includes(d.status)} onClick={save}>{pending?'Thử lại cùng giao dịch':'Lưu chỉnh sửa'}</Button></div>;}
