import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { NavLink } from '@/components/NavLink';
import { customsDb,customsChecked,customsManage } from './customs-api';
import { CustomsStyles } from './CustomsStyles';
export function AdminCustoms(){
 const [products,setProducts]=useState<any[]>([]),[signature,setSignature]=useState(''),[name,setName]=useState(''),[selected,setSelected]=useState(''),[editName,setEditName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let live=true;customsChecked(customsDb.from('customs_products').select('signature,name,enabled').order('signature')).then(data=>{if(live)setProducts(data||[]);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[revision]);
 const product=products.find(p=>p.signature===selected);
 useEffect(()=>{setEditName(product?.name||'');},[selected,product?.name]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();setRevision(r=>r+1);}catch(e){setError(e instanceof Error?e.message:'Thao tác thất bại');}finally{setBusy(false);}}
 return <section className="customs-workspace"><CustomsStyles/><header><h3 className="text-xl">Sản phẩm Customs</h3><p className="text-sm text-muted-foreground">Mỗi sản phẩm có chữ ký riêng. Tạo và quản lý key trong Licenses.</p></header>{error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
 <div className="customs-card"><h4>Thêm sản phẩm</h4><div className="customs-fields"><label>Chữ ký / mã sản phẩm<Input maxLength={24} placeholder="Nhập mã sản phẩm" value={signature} onChange={e=>setSignature(e.target.value.toUpperCase())}/></label><label>Tên sản phẩm<Input maxLength={100} placeholder="Tên app, tool hoặc menu" value={name} onChange={e=>setName(e.target.value)}/></label></div><Button disabled={busy} onClick={()=>run(async()=>{if(!/^[A-Z][A-Z0-9]{2,23}$/.test(signature))throw new Error('Mã cần 3–24 ký tự A–Z, 0–9; bắt đầu bằng chữ.');await customsManage('product_create',signature,null,{name});setSelected(signature);setSignature('');setName('');})}>Thêm sản phẩm</Button></div>
 <div className="customs-card"><h4>Quản lý sản phẩm</h4><label>Sản phẩm<select disabled={busy} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Chọn sản phẩm</option>{products.map(p=><option key={p.signature} value={p.signature}>{p.name} · {p.signature}{p.enabled?'':' · Đang tắt'}</option>)}</select></label>{product&&<><label>Tên sản phẩm<Input maxLength={100} value={editName} onChange={e=>setEditName(e.target.value)}/></label><p className="text-sm">Chữ ký: <strong>{product.signature}</strong> · {product.enabled?'Đang bật':'Đang tắt'}</p><p className="text-xs text-muted-foreground">Chữ ký cố định để key và app hiện tại tiếp tục dùng đúng sản phẩm.</p><div className="customs-actions"><Button disabled={busy} onClick={()=>run(async()=>{await customsManage('product_update',selected,null,{name:editName,enabled:product.enabled});})}>Lưu tên</Button><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{await customsManage('product_update',selected,null,{name:product.name,enabled:!product.enabled});})}>{product.enabled?'Tắt sản phẩm':'Bật sản phẩm'}</Button><Button asChild><NavLink to={'/licenses2/new?customs='+selected}>Tạo key</NavLink></Button><Button variant="outline" asChild><NavLink to={'/licenses2?customs='+selected}>Danh sách key</NavLink></Button><Button variant="destructive" disabled={busy} onClick={()=>{if(window.prompt('Xóa vĩnh viễn sản phẩm và TẤT CẢ key/thiết bị/phiên. Nhập '+selected)===selected)void run(async()=>{await customsManage('product_delete',selected,null,{confirm:selected});setSelected('');});}}>Xóa sản phẩm</Button></div></>}</div>
 </section>;
}
