import { useCallback,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { TurnstileWidget } from '@/components/turnstile/TurnstileWidget';
import { customsPublic } from './customs-api';
import { CustomsStyles } from './CustomsStyles';
export function CustomsPublicReset(){
 const [key,setKey]=useState(''),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[token,setToken]=useState<string|null>(null),[nonce,setNonce]=useState(0);
 const onToken=useCallback((t:string|null)=>setToken(t),[]);const siteKey=String(import.meta.env.VITE_TURNSTILE_SITE_KEY||'').trim();
 async function run(action:'info'|'reset'){if(busy)return;const normalized=key.replace(/\s+/g,'').toUpperCase();if(!/^[A-Z][A-Z0-9]{2,23}-[A-F0-9]{32}$/.test(normalized)){setError('Định dạng key Customs không hợp lệ.');return;}if(action==='reset'&&!window.confirm('Reset thiết bị, thu hồi phiên và trừ thời gian theo quy định key?'))return;setBusy(true);setError('');setResult(null);try{setResult(await customsPublic(action,normalized,token));}catch(e){setError(e instanceof Error?e.message:'Thao tác thất bại');}finally{setBusy(false);if(action==='reset'){setToken(null);setNonce(n=>n+1);}}}
 return <section className="customs-workspace"><CustomsStyles/><div className="customs-card"><h3>Thông tin / Reset key Customs</h3><label>Key<Input autoComplete="off" value={key} onChange={e=>{setKey(e.target.value);setResult(null);setError('');}} placeholder="Nhập key muốn reset"/></label><p className="text-sm text-muted-foreground">Reset không bắt đầu lại thời hạn. Phiên và thiết bị cũ được thu hồi.</p>{siteKey?<TurnstileWidget key={nonce} siteKey={siteKey} onTokenChange={onToken}/>:<p className="text-sm">Chưa cấu hình xác minh reset. Vẫn có thể kiểm tra thông tin.</p>}<div className="customs-actions"><Button disabled={busy} onClick={()=>run('info')}>Kiểm tra key</Button><Button variant="outline" disabled={busy||!token||!siteKey||result?.public_reset_disabled===true} onClick={()=>run('reset')}>Reset thiết bị</Button></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}</div>
 {result&&<div className="customs-card"><h4>{result.signature} · {result.status}</h4><p>Thiết bị: {result.device_count}/{result.max_devices}</p><p>Kích hoạt: {result.activated_at?new Date(result.activated_at).toLocaleString():'Chưa kích hoạt'}</p><p>Hết hạn: {result.expires_at?new Date(result.expires_at).toLocaleString():'Chưa bắt đầu'}</p><p>Reset public: {result.public_reset_disabled?'Đã cấm':'Được phép'} · Đã reset {result.public_reset_count} lần</p><p>Trừ thời gian còn lại: {result.reset_penalty_pct}% · Giới hạn: {result.public_reset_limit||'Không giới hạn'}</p>{result.next_reset_at&&<p>Lần reset tiếp theo: {new Date(result.next_reset_at).toLocaleString()}</p>}{result.devices_removed>0&&<p>Đã gỡ {result.devices_removed} thiết bị; trừ {result.penalty_seconds} giây.</p>}</div>}
 </section>;
}
