import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { customsDb,customsChecked,customsManage,customsKey } from './customs-api';
import { CustomsStyles } from './CustomsStyles';
type KeyRow={id:string;signature:string;key_hint:string;license_type:string;duration_seconds:number;expires_at:string|null;activated_at:string|null;enabled:boolean;max_devices:number;note:string;deleted_at:string|null;public_reset_disabled:boolean;reset_cooldown_seconds:number;reset_penalty_pct:number;public_reset_limit:number;public_reset_count:number;admin_reset_count:number;created_at:string;key_source:string};
const fields='id,signature,key_hint,license_type,duration_seconds,expires_at,activated_at,enabled,max_devices,note,deleted_at,public_reset_disabled,reset_cooldown_seconds,reset_penalty_pct,public_reset_limit,public_reset_count,admin_reset_count,created_at,key_source';
const localDate=(s:string|null)=>s?new Date(new Date(s).getTime()-new Date(s).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
export function CustomsLicenses({signature,mode='list',countdownOnly=false}:{signature:string;mode?:'list'|'create'|'trash';countdownOnly?:boolean}){
 const [rows,setRows]=useState<KeyRow[]>([]),[revision,setRevision]=useState(0),[page,setPage]=useState(0),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[raw,setRaw]=useState('');
 const [editing,setEditing]=useState<KeyRow|null>(null),[detail,setDetail]=useState<KeyRow|null>(null),[devices,setDeviceRows]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
 const [hours,setHours]=useState('24'),[maxDevices,setMaxDevices]=useState('1'),[licenseType,setLicenseType]=useState('first_use'),[expires,setExpires]=useState(''),[note,setNote]=useState(''),[enabled,setEnabled]=useState(true),[renewHours,setRenewHours]=useState('24'),[keySource,setKeySource]=useState('admin'),[sourceFilter,setSourceFilter]=useState('all'),[auditPage,setAuditPage]=useState(0);
 useEffect(()=>{setPage(0);setEditing(null);setDetail(null);setRaw('');setError('');},[signature,mode]);
 useEffect(()=>{let live=true;setRows([]);let query=customsDb.from('customs_keys').select(fields).eq('signature',signature).order('created_at',{ascending:false}).order('id',{ascending:false}).range(page*20,page*20+19);query=mode==='trash'?query.not('deleted_at','is',null):query.is('deleted_at',null);if(sourceFilter!=='all')query=query.eq('key_source',sourceFilter);if(q.trim()){const escaped=q.trim().replace(/[\\%_,()]/g,'');query=query.or('key_hint.ilike.%'+escaped+'%,note.ilike.%'+escaped+'%');}customsChecked(query).then(data=>{if(live)setRows(data||[]);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[signature,page,revision,mode,sourceFilter,q]);
 useEffect(()=>{let live=true;setDeviceRows([]);setAudit([]);if(detail){Promise.all([customsChecked(customsDb.from('customs_devices').select('device_hash,first_seen').eq('key_id',detail.id)),customsChecked(customsDb.from('customs_audit').select('action,detail,created_at').eq('key_id',detail.id).order('created_at',{ascending:false}).order('id',{ascending:false}).range(auditPage*30,auditPage*30+29))]).then(([d,a])=>{if(live){setDeviceRows(d||[]);setAudit(a||[]);}}).catch(e=>{if(live)setError(e.message);});}return()=>{live=false;};},[detail,revision,auditPage]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();setRevision(r=>r+1);}catch(e){setError(e instanceof Error?e.message:'Thao tác thất bại');}finally{setBusy(false);}}
 function edit(k:KeyRow){setEditing(k);setHours(String(k.duration_seconds/3600));setMaxDevices(String(k.max_devices));setLicenseType(k.license_type);setExpires(localDate(k.expires_at));setNote(k.note);setEnabled(k.enabled);setKeySource(k.key_source||'admin');setRaw('');}
 function fresh(){setEditing(null);setHours('24');setMaxDevices('1');setLicenseType('first_use');setExpires('');setNote('');setEnabled(true);setKeySource('admin');}
 async function save(){await run(async()=>{const seconds=Number(hours)*3600,devs=Number(maxDevices);if(!Number.isInteger(seconds)||seconds<60||seconds>31536000||!Number.isInteger(devs)||devs<1||devs>20)throw new Error('Kiểm tra thời hạn và số thiết bị.');
 const data:any={duration_seconds:seconds,max_devices:devs,note,enabled,key_source:keySource};
 if(editing){if(expires)data.expires_at=new Date(expires).toISOString();await customsManage('update',signature,editing.id,data);setEditing(null);}else{const key=await customsKey(signature);Object.assign(data,{key_hash:key.hash,key_hint:key.hint,license_type:licenseType});if(licenseType==='fixed'){data.expires_at=expires?new Date(expires).toISOString():new Date(Date.now()+seconds*1000).toISOString();}await customsManage('create',signature,null,data);setRaw(key.raw);setPage(0);}
 });}
 async function action(kind:string,k:KeyRow,data:any={}){await run(async()=>{await customsManage(kind,signature,k.id,data);if(detail?.id===k.id)setDetail(null);if(editing?.id===k.id)setEditing(null);setRaw('');});}
 const matches=rows;
 return <section className="customs-workspace"><CustomsStyles/>
 <header><h3 className="text-xl">Customs · {signature}</h3><p className="text-sm text-muted-foreground">Quản lý key độc lập với SUNNY. Nguyên key chỉ hiển thị lúc tạo.</p></header>
 {error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
 {mode!=='trash'&&(mode==='create'||editing)&&<div className="customs-card"><h4>{editing?'Sửa license':'Tạo license'}</h4>
 <div className="customs-fields"><label>Loại thời hạn<select disabled={!!editing||busy} value={licenseType} onChange={e=>setLicenseType(e.target.value)}><option value="first_use">Tính từ lần đăng nhập đầu</option><option value="fixed">Kích hoạt ngay</option></select></label><label>Thời lượng (giờ)<Input type="number" step="any" value={hours} onChange={e=>setHours(e.target.value)}/></label><label>Số thiết bị<Input type="number" min="1" max="20" value={maxDevices} onChange={e=>setMaxDevices(e.target.value)}/></label>{(licenseType==='fixed'||editing?.activated_at)&&<label>Thời điểm hết hạn<Input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/>{!editing&&<span className="text-xs text-muted-foreground">Để trống: tính từ bây giờ theo thời lượng đã chọn.</span>}</label>}</div>
 <label>Ghi chú<Input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><label className="customs-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Key đang bật</label><label>Nhóm key<select value={keySource} disabled={busy} onChange={e=>setKeySource(e.target.value)}><option value="admin">Key admin</option><option value="free">Key vượt</option></select></label><p className="text-xs text-muted-foreground">Reset dùng chính sách chung trong Reset Settings.</p>
 <div className="customs-actions"><Button disabled={busy} onClick={save}>{editing?'Lưu thay đổi':'Tạo key '+signature}</Button>{editing&&<Button variant="outline" disabled={busy} onClick={fresh}>Hủy sửa</Button>}</div><p className="text-xs text-muted-foreground">Sửa key thu hồi phiên hiện tại. Thay thời lượng của key đã kích hoạt không đổi hạn; dùng Gia hạn hoặc sửa thời điểm hết hạn.</p>
 </div>}
 {raw&&<div className="customs-card"><h4>Key mới · lưu ngay</h4><code className="break-all">{raw}</code><Button disabled={busy} onClick={()=>run(async()=>{await navigator.clipboard.writeText(raw);})}>Sao chép key</Button></div>}
 <div className="customs-card"><div className="customs-actions"><h4>{mode==='trash'?'Thùng rác':'Danh sách key'}</h4><Button variant="outline" disabled={busy} onClick={()=>setRevision(r=>r+1)}>Tải lại</Button></div><div className="customs-fields"><label>Nhóm key<select value={sourceFilter} onChange={e=>{setSourceFilter(e.target.value);setPage(0);}}><option value="all">Tất cả</option><option value="admin">Key admin</option><option value="free">Key vượt</option></select></label><label>Tìm kiếm<Input value={q} onChange={e=>{setQ(e.target.value);setPage(0);}} placeholder="Tìm mã / ghi chú toàn bộ sản phẩm"/></label></div>
 {!matches.length&&<p className="text-sm text-muted-foreground">Không có key trên trang này.</p>}
 {matches.map(k=><div className="customs-row" key={k.id}><div><p className="font-mono text-sm">{k.key_hint||k.signature+' · '+k.id.slice(0,8)}</p><p className="text-sm">{k.key_source==='free'?'Key vượt':'Key admin'} · {k.license_type==='first_use'?'Dùng mới tính giờ':'Kích hoạt ngay'} · {k.duration_seconds/3600} giờ · {k.max_devices} thiết bị</p><p className="text-sm">{!k.enabled?'Đã khóa':k.expires_at&&new Date(k.expires_at).getTime()<=Date.now()?'Đã hết hạn':k.expires_at?'Hết hạn: '+new Date(k.expires_at).toLocaleString():'Chưa kích hoạt'}</p><p className="text-sm text-muted-foreground">{k.note}</p></div><div className="customs-actions"><Button variant="outline" disabled={busy} onClick={()=>{setAuditPage(0);setDetail(k);}}>Thông tin</Button>{mode==='trash'?<><Button disabled={busy} onClick={()=>action('restore',k)}>Khôi phục</Button><Button variant="destructive" disabled={busy} onClick={()=>{if(window.prompt('Xóa vĩnh viễn key. Nhập mã sản phẩm '+signature)===signature)void action('delete',k,{confirm:signature});}}>Xóa vĩnh viễn</Button></>:<><Button variant="outline" disabled={busy} onClick={()=>edit(k)}>Sửa</Button><Button variant="outline" disabled={busy} onClick={()=>action('update',k,{enabled:!k.enabled})}>{k.enabled?'Khóa':'Bật'}</Button><Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Reset thiết bị và thu hồi phiên; giữ nguyên hạn key?'))void action('reset',k);}}>Reset thiết bị</Button><Button variant="destructive" disabled={busy} onClick={()=>{if(window.confirm('Đưa key vào thùng rác và thu hồi thiết bị/phiên?'))void action('trash',k);}}>Xóa</Button></>}</div></div>)}
 <div className="customs-actions"><Button variant="outline" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Trước</Button><span className="self-center text-sm">Trang {page+1}</span><Button variant="outline" disabled={rows.length<20||busy} onClick={()=>setPage(p=>p+1)}>Sau</Button></div></div>
 {detail&&<div className="customs-card"><div className="customs-actions"><h4>Thông tin key</h4><Button variant="outline" onClick={()=>setDetail(null)}>Đóng</Button></div><p className="font-mono text-sm">ID: {detail.id}</p><p className="text-sm">Chữ ký: {detail.signature} · Tạo: {new Date(detail.created_at).toLocaleString()}</p><p className="text-sm">Kích hoạt: {detail.activated_at?new Date(detail.activated_at).toLocaleString():'Chưa kích hoạt'} · Hết hạn: {detail.expires_at?new Date(detail.expires_at).toLocaleString():'Chưa bắt đầu'}</p><p className="text-sm">Reset admin: {detail.admin_reset_count} · Public: {detail.public_reset_count}</p>
 {mode!=='trash'&&<><label>Gia hạn thêm (giờ)<Input type="number" step="any" value={renewHours} onChange={e=>setRenewHours(e.target.value)}/></label><div className="customs-actions"><Button disabled={busy} onClick={()=>{const seconds=Number(renewHours)*3600;if(!Number.isInteger(seconds)||seconds<60||seconds>31536000){setError('Thời gian gia hạn không hợp lệ');return;}void action('renew',detail,{seconds});}}>Gia hạn</Button>{detail.license_type==='first_use'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.prompt('Bắt đầu lại thời hạn từ lần login tiếp theo. Nhập '+signature)===signature)void action('reset_activation',detail,{confirm:signature});}}>Reset kích hoạt</Button>}</div></>}
 <h4>Thiết bị ({devices.length})</h4>{devices.map(d=><div className="customs-row" key={d.device_hash}><code className="text-xs break-all">{d.device_hash}</code><p className="text-xs">{new Date(d.first_seen).toLocaleString()}</p>{mode!=='trash'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Gỡ thiết bị này và thu hồi phiên của nó?'))void action('remove_device',detail,{device_hash:d.device_hash});}}>Gỡ thiết bị</Button>}</div>)}
 <h4>Lịch sử key</h4>{audit.map((a,i)=><p className="text-xs" key={i}>{new Date(a.created_at).toLocaleString()} · {a.action}</p>)}
 <div className="customs-actions"><Button variant="outline" disabled={!auditPage} onClick={()=>setAuditPage(p=>p-1)}>Log trước</Button><span>Trang {auditPage+1}</span><Button variant="outline" disabled={audit.length<30} onClick={()=>setAuditPage(p=>p+1)}>Log sau</Button></div></div>}
 </section>;
}
