import {KeyCopy,SavedKey} from '@/features/licenses/KeyCopy';
import { convertDuration,DurationUnit,durationFactors } from "@/features/licenses/duration-units";
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Link } from 'react-router-dom';
import { DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator } from '@/components/ui/dropdown-menu';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { customsDb,customsChecked,customsManage,customsKey } from './customs-api';
import { CustomsStyles } from './CustomsStyles';
type KeyRow={id:string;signature:string;key_hint:string;license_type:string;duration_seconds:number;expires_at:string|null;activated_at:string|null;enabled:boolean;max_devices:number;note:string;deleted_at:string|null;public_reset_disabled:boolean;reset_cooldown_seconds:number;reset_penalty_pct:number;public_reset_limit:number;public_reset_count:number;admin_reset_count:number;created_at:string;key_source:string};
const fields='id,signature,key_hint,license_type,duration_seconds,expires_at,activated_at,enabled,max_devices,note,deleted_at,public_reset_disabled,reset_cooldown_seconds,reset_penalty_pct,public_reset_limit,public_reset_count,admin_reset_count,created_at,key_source';
const localDate=(s:string|null)=>s?new Date(new Date(s).getTime()-new Date(s).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
export function CustomsLicenses({signature,mode='list',countdownOnly=false}:{signature:string;mode?:'list'|'create'|'trash';countdownOnly?:boolean}){
 const [rows,setRows]=useState<KeyRow[]>([]),[revision,setRevision]=useState(0),[page,setPage]=useState(0),[q,setQ]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[raw,setRaw]=useState('');
 const [editing,setEditing]=useState<KeyRow|null>(null),[detail,setDetail]=useState<KeyRow|null>(null),[devices,setDeviceRows]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
 const [draftKey,setDraftKey]=useState('');
 const [durationUnit,setDurationUnit]=useState<DurationUnit>('hours');
 const [hours,setHours]=useState('24'),[maxDevices,setMaxDevices]=useState('1'),[licenseType,setLicenseType]=useState('first_use'),[expires,setExpires]=useState(''),[note,setNote]=useState(''),[enabled,setEnabled]=useState(true),[renewHours,setRenewHours]=useState('24'),[keySource,setKeySource]=useState('admin'),[sourceFilter,setSourceFilter]=useState('all'),[auditPage,setAuditPage]=useState(0);
 useEffect(()=>{setPage(0);setEditing(null);setDetail(null);setRaw('');setDraftKey('');setError('');},[signature,mode]);
 useEffect(()=>{let live=true;setRows([]);if(mode==='create')return;let query=customsDb.from('customs_keys').select(fields).eq('signature',signature).order('created_at',{ascending:false}).order('id',{ascending:false}).range(page*20,page*20+19);query=mode==='trash'?query.not('deleted_at','is',null):query.is('deleted_at',null);if(sourceFilter!=='all')query=query.eq('key_source',sourceFilter);if(q.trim()){const escaped=q.trim().replace(/[\\%_,()]/g,'');query=query.or('key_hint.ilike.%'+escaped+'%,note.ilike.%'+escaped+'%');}customsChecked(query).then(data=>{if(live)setRows(data||[]);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[signature,page,revision,mode,sourceFilter,q]);
 useEffect(()=>{let live=true;setDeviceRows([]);setAudit([]);if(detail){Promise.all([customsChecked(customsDb.from('customs_devices').select('device_hash,first_seen').eq('key_id',detail.id)),customsChecked(customsDb.from('customs_audit').select('action,detail,created_at').eq('key_id',detail.id).order('created_at',{ascending:false}).order('id',{ascending:false}).range(auditPage*30,auditPage*30+29))]).then(([d,a])=>{if(live){setDeviceRows(d||[]);setAudit(a||[]);}}).catch(e=>{if(live)setError(e.message);});}return()=>{live=false;};},[detail,revision,auditPage]);
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();setRevision(r=>r+1);}catch(e){setError(e instanceof Error?e.message:'Thao tác thất bại');}finally{setBusy(false);}}
 function edit(k:KeyRow){setEditing(k);setDurationUnit("hours");setHours(String(k.duration_seconds/3600));setMaxDevices(String(k.max_devices));setLicenseType(k.license_type);setExpires(localDate(k.expires_at));setNote(k.note);setEnabled(k.enabled);setKeySource(k.key_source||'admin');setRaw('');}
 function fresh(){setEditing(null);setDurationUnit('hours');setHours('24');setMaxDevices('1');setLicenseType('first_use');setExpires('');setNote('');setEnabled(true);setKeySource('admin');}
 async function save(){await run(async()=>{const seconds=Math.round(Number(hours)*durationFactors[durationUnit]),devs=Number(maxDevices);if(!Number.isInteger(seconds)||seconds<60||seconds>31536000||!Number.isInteger(devs)||devs<1||devs>2147483647)throw new Error('Kiểm tra thời hạn và số thiết bị.');
 const data:any={duration_seconds:seconds,max_devices:devs,note,enabled,key_source:keySource};
 if(editing){data.license_type=licenseType;if(licenseType!==editing.license_type){if(!window.confirm(licenseType==='fixed'?'Chuyển sang kích hoạt ngay? Thời hạn bắt đầu từ bây giờ (hoặc hạn bạn chọn), thiết bị/phiên cũ sẽ được thu hồi.':'Chuyển sang dùng mới tính giờ? Key sẽ chờ lần đăng nhập tiếp theo, thiết bị/phiên cũ sẽ được thu hồi.'))return;data.confirm_type_change=signature;}if(expires)data.expires_at=new Date(expires).toISOString();await customsManage('update',signature,editing.id,data);setEditing(null);}else{if(!draftKey.trim())throw new Error('Nhập key hoặc bấm Generate trước.');const key=await customsKey(signature,draftKey);Object.assign(data,{key_hash:key.hash,key_hint:key.hint,raw_key:key.raw,license_type:licenseType});if(licenseType==='fixed'){data.expires_at=expires?new Date(expires).toISOString():new Date(Date.now()+seconds*1000).toISOString();}await customsManage('create',signature,null,data);setRaw(key.raw);setPage(0);}
 });}
 async function action(kind:string,k:KeyRow,data:any={}){await run(async()=>{await customsManage(kind,signature,k.id,data);if(detail?.id===k.id)setDetail(null);if(editing?.id===k.id)setEditing(null);setRaw('');});}
 const editor=<div className="customs-card"><h4>{editing?'Sửa license':'Tạo license'}</h4>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
 {!editing&&<div className="grid gap-2"><div className="flex items-center justify-between gap-3"><label htmlFor="customs-key-draft">Key</label><Button variant="outline" disabled={busy} onClick={()=>run(async()=>{setDraftKey((await customsKey(signature)).raw);})}>Generate</Button></div><Input id="customs-key-draft" disabled={busy} value={draftKey} onChange={e=>setDraftKey(e.target.value)} placeholder={signature+'-…'} autoCapitalize="characters"/><p className="text-xs text-muted-foreground">Nhập key riêng hoặc Generate. Mã sản phẩm + 32 ký tự 0–9, A–F.</p></div>}<div className="customs-fields"><label>Loại thời hạn<select disabled={busy} value={licenseType} onChange={e=>{setLicenseType(e.target.value);if(editing&&e.target.value!==editing.license_type)setExpires('');}}><option value="first_use">Tính từ lần đăng nhập đầu</option><option value="fixed">Kích hoạt ngay</option></select></label><label>Thời lượng<Input type="number" step="any" value={hours} onChange={e=>setHours(e.target.value)}/><select aria-label="Đơn vị thời gian" value={durationUnit} onChange={e=>{const next=e.target.value as DurationUnit;setHours(String(convertDuration(Number(hours),durationUnit,next)));setDurationUnit(next);}}><option value="minutes">Phút</option><option value="hours">Giờ</option><option value="days">Ngày</option></select></label><label>Số thiết bị<Input type="number" min="1"  value={maxDevices} onChange={e=>setMaxDevices(e.target.value)}/></label>{(licenseType==='fixed'||(editing?.activated_at&&licenseType===editing?.license_type))&&<label>Thời điểm hết hạn<Input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)}/>{!editing&&<span className="text-xs text-muted-foreground">Để trống: tính từ bây giờ theo thời lượng đã chọn.</span>}</label>}</div>
 <label>Ghi chú<Input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><label className="customs-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Key đang bật</label><label>Nhóm key<select value={keySource} disabled={busy} onChange={e=>setKeySource(e.target.value)}><option value="admin">Key admin</option><option value="free">Key vượt</option></select></label><p className="text-xs text-muted-foreground">Reset dùng chính sách chung trong Reset Settings.</p>{editing&&licenseType!==editing.license_type&&<p className="text-sm text-amber-800">Đổi loại sẽ thu hồi thiết bị và phiên cũ. {licenseType==='fixed'?'Thời hạn bắt đầu từ bây giờ hoặc hạn được chọn.':'Thời hạn bắt đầu ở lần đăng nhập tiếp theo.'}</p>}
 <div className="customs-actions"><Button disabled={busy||(!editing&&!draftKey.trim())} onClick={save}>{editing?'Lưu thay đổi':'Tạo key '+signature}</Button>{editing&&<Button variant="outline" disabled={busy} onClick={fresh}>Hủy sửa</Button>}</div><p className="text-xs text-muted-foreground">Sửa key thu hồi phiên hiện tại. Nếu giữ nguyên loại, thay thời lượng không đổi hạn đang chạy; dùng Gia hạn để thêm giờ.</p>
 </div>;
 const matches=rows;
 return <section className="customs-workspace"><CustomsStyles/>
 <header><h3 className="text-xl">Customs · {signature}</h3><p className="text-sm text-muted-foreground">Quản lý key độc lập với SUNNY. Key mới được lưu có mã hóa để xem lại trong Thông tin key.</p></header>
 {error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
 {mode==='create'&&editor}
 {editing&&mode!=='create'&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setEditing(null);}}><DialogContent aria-describedby={undefined} className="customs-key-dialog max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Sửa license · {signature}</DialogTitle></DialogHeader><div className="customs-workspace">{editor}</div></DialogContent></Dialog>}
 {raw&&<div className="customs-card"><h4>Key mới · lưu ngay</h4><code className="break-all">{raw}</code><KeyCopy value={raw}/><Link className="text-sm font-medium underline" to={'/licenses?customs='+encodeURIComponent(signature)}>Mở danh sách key</Link></div>}
 {mode!=='create'&&<div className="customs-card"><div className="customs-actions"><h4>{mode==='trash'?'Thùng rác':'Danh sách key'}</h4><Button variant="outline" disabled={busy} onClick={()=>setRevision(r=>r+1)}>Tải lại</Button></div><div className="customs-fields"><label>Nhóm key<select value={sourceFilter} onChange={e=>{setSourceFilter(e.target.value);setPage(0);}}><option value="all">Tất cả</option><option value="admin">Key admin</option><option value="free">Key vượt</option></select></label><label>Tìm kiếm<Input value={q} onChange={e=>{setQ(e.target.value);setPage(0);}} placeholder="Tìm mã / ghi chú toàn bộ sản phẩm"/></label></div>
 {!matches.length&&<p className="text-sm text-muted-foreground">Không có key trên trang này.</p>}
 {matches.map(k=><div className="customs-row" key={k.id}><div><p className="font-mono text-sm">{k.key_hint||k.signature+' · '+k.id.slice(0,8)}</p><p className="text-sm">{k.key_source==='free'?'Key vượt':'Key admin'} · {k.license_type==='first_use'?'Dùng mới tính giờ':'Kích hoạt ngay'} · {k.duration_seconds/3600} giờ · {k.max_devices} thiết bị</p><p className="text-sm">{!k.enabled?'Đã khóa':k.expires_at&&new Date(k.expires_at).getTime()<=Date.now()?'Đã hết hạn':k.expires_at?'Hết hạn: '+new Date(k.expires_at).toLocaleString():'Chưa kích hoạt'}</p><p className="text-sm text-muted-foreground">{k.note}</p></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" disabled={busy} aria-label={'Actions · '+k.key_hint}>Actions</Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="customs-key-menu"><DropdownMenuItem onSelect={()=>{setAuditPage(0);setDetail(k);}}>Thông tin / Gia hạn</DropdownMenuItem>{mode==='trash'?<><DropdownMenuItem onSelect={()=>void action('restore',k)}>Khôi phục</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive" onSelect={()=>{if(window.prompt('Xóa vĩnh viễn key. Nhập mã sản phẩm '+signature)===signature)void action('delete',k,{confirm:signature});}}>Xóa vĩnh viễn</DropdownMenuItem></>:<><DropdownMenuItem onSelect={()=>edit(k)}>Sửa</DropdownMenuItem><DropdownMenuItem onSelect={()=>void action('update',k,{enabled:!k.enabled})}>{k.enabled?'Khóa':'Bật'}</DropdownMenuItem><DropdownMenuItem onSelect={()=>{if(window.confirm('Reset thiết bị và thu hồi phiên; giữ nguyên hạn key?'))void action('reset',k);}}>Reset thiết bị</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive" onSelect={()=>{if(window.confirm('Đưa key vào thùng rác và thu hồi thiết bị/phiên?'))void action('trash',k);}}>Xóa</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu></div>)}
 <div className="customs-actions"><Button variant="outline" disabled={!page||busy} onClick={()=>setPage(p=>p-1)}>Trước</Button><span className="self-center text-sm">Trang {page+1}</span><Button variant="outline" disabled={rows.length<20||busy} onClick={()=>setPage(p=>p+1)}>Sau</Button></div></div>}
 {detail&&<Dialog open onOpenChange={open=>{if(!open&&!busy)setDetail(null);}}><DialogContent aria-describedby={undefined} className="customs-key-dialog max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Thông tin key · {signature}</DialogTitle></DialogHeader><div className="customs-workspace"><div className="customs-card"><div className="customs-actions"><h4>Thông tin key</h4><Button variant="outline" onClick={()=>setDetail(null)}>Đóng</Button></div><SavedKey key={detail.id} id={detail.id} hint={detail.key_hint}/><p className="font-mono text-sm break-all">ID: {detail.id}</p><p className="text-sm">Chữ ký: {detail.signature} · Tạo: {new Date(detail.created_at).toLocaleString()}</p><p className="text-sm">Kích hoạt: {detail.activated_at?new Date(detail.activated_at).toLocaleString():'Chưa kích hoạt'} · Hết hạn: {detail.expires_at?new Date(detail.expires_at).toLocaleString():'Chưa bắt đầu'}</p><p className="text-sm">Reset admin: {detail.admin_reset_count} · Public: {detail.public_reset_count}</p>
 {mode!=='trash'&&<><label>Gia hạn thêm (giờ)<Input type="number" step="any" value={renewHours} onChange={e=>setRenewHours(e.target.value)}/></label><div className="customs-actions"><Button disabled={busy} onClick={()=>{const seconds=Number(renewHours)*3600;if(!Number.isInteger(seconds)||seconds<60||seconds>31536000){setError('Thời gian gia hạn không hợp lệ');return;}void action('renew',detail,{seconds});}}>Gia hạn</Button>{detail.license_type==='first_use'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.prompt('Bắt đầu lại thời hạn từ lần login tiếp theo. Nhập '+signature)===signature)void action('reset_activation',detail,{confirm:signature});}}>Reset kích hoạt</Button>}</div></>}
 <h4>Thiết bị ({devices.length})</h4>{devices.map(d=><div className="customs-row" key={d.device_hash}><code className="text-xs break-all">{d.device_hash}</code><p className="text-xs">{new Date(d.first_seen).toLocaleString()}</p>{mode!=='trash'&&<Button variant="outline" disabled={busy} onClick={()=>{if(window.confirm('Gỡ thiết bị này và thu hồi phiên của nó?'))void action('remove_device',detail,{device_hash:d.device_hash});}}>Gỡ thiết bị</Button>}</div>)}
 <h4>Lịch sử key</h4>{audit.map((a,i)=><p className="text-xs" key={i}>{new Date(a.created_at).toLocaleString()} · {a.action}</p>)}
 <div className="customs-actions"><Button variant="outline" disabled={!auditPage} onClick={()=>setAuditPage(p=>p-1)}>Log trước</Button><span>Trang {auditPage+1}</span><Button variant="outline" disabled={audit.length<30} onClick={()=>setAuditPage(p=>p+1)}>Log sau</Button></div></div></div></DialogContent></Dialog>}
 </section>;
}
