import {KeyInformation} from '@/features/licenses/KeyInformation';
import { useCallback,useEffect,useState } from 'react';
import { PublicHeader } from '@/features/support/SupportViews';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { TurnstileWidget } from '@/components/turnstile/TurnstileWidget';
import { CustomsStyles } from '@/features/customs/CustomsStyles';
import { normalizeResetKey,publicKeyAction,resetRuntime } from '@/features/customs/reset-api';
const messages:Record<string,string>={TURNSTILE_CONFIG_INVALID:'Secret xác minh của dịch vụ không hợp lệ. Admin cần kiểm tra lại widget.',TURNSTILE_INVALID:'Xác minh đã hết hạn hoặc không hợp lệ. Vui lòng xác minh lại.',TURNSTILE_FAILED:'Xác minh không hợp lệ. Vui lòng xác minh lại.',TURNSTILE_REQUIRED:'Vui lòng hoàn tất xác minh.',RESET_DISABLED:'Reset đang tắt hoặc key không được phép reset.',KEY_RESET_DISABLED:'Key này đã bị khóa reset.',KEY_UNAVAILABLE:'Key không khả dụng. Kiểm tra lại key.',PRODUCT_DISABLED:'Sản phẩm đang tắt hoặc không tồn tại.',KEY_DISABLED:'Key đã bị khóa.',RESET_COOLDOWN:'Chưa đến lượt reset tiếp theo.',RESET_LIMIT:'Đã đạt giới hạn reset.',RATE_LIMIT:'Bạn thao tác quá nhanh. Vui lòng chờ rồi thử lại.',NO_DEVICES:'Key chưa có thiết bị cần reset.',RESET_NOT_CONFIGURED:'Dịch vụ reset chưa sẵn sàng.',SERVICE_UNAVAILABLE:'Không kết nối được dịch vụ. Vui lòng thử lại.'};
const dates=(v:any)=>v?new Date(v).toLocaleString('vi-VN'):'Chưa bắt đầu';
export function ResetKeyPage(){
 const [key,setKey]=useState(''),[token,setToken]=useState<string|null>(null),[captcha,setCaptcha]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<any>(null),[runtime,setRuntime]=useState<any>(null),[runtimeError,setRuntimeError]=useState('');
 const onToken=useCallback((v:string|null)=>setToken(v),[]);const siteKey=String(import.meta.env.VITE_TURNSTILE_SITE_KEY||runtime?.site_key||'').trim();const requires=runtime?.turnstile_enabled!==false;
 useEffect(()=>{let live=true;resetRuntime().then(d=>{if(live)setRuntime(d);}).catch(()=>{if(live)setRuntimeError('Không đọc được cấu hình reset. Tải lại trang để thử tiếp.');});return()=>{live=false;};},[]);
 async function run(action:'info'|'reset'){
  if(busy)return;const raw=normalizeResetKey(key);if(!raw){setError('Nhập key muốn kiểm tra hoặc reset.');return;}
  if(action==='reset'&&requires&&!token){setError(messages.TURNSTILE_REQUIRED);return;}
  if(action==='reset'&&!window.confirm('Reset thiết bị của key này? Thời hạn sẽ áp dụng theo chính sách reset hiện tại.'))return;
  setBusy(true);setError('');setResult(null);const proof=token;if(action==='reset')setToken(null);
  try{const d=await publicKeyAction(action,raw,proof||undefined);if(d.ok!==true){setError(d.disabled_message||messages[d.code||d.msg]||d.code||d.msg||'Thao tác chưa hoàn tất.');}else {setResult({...d,resetDone:action==='reset'});if(action==='reset'){try{const snapshot=await publicKeyAction('info',raw);if(snapshot.ok===true)setResult({...snapshot,resetDone:true});}catch{setError('Reset thành công, chưa tải lại được thông tin. Bấm Kiểm tra key để cập nhật.');}}}}catch(e){const code=e instanceof Error?e.message:'';setError(messages[code]||code||'Không kết nối được dịch vụ.');}finally{setBusy(false);if(action==='reset')setCaptcha(v=>v+1);}
 }
 return <div className="sunny-public min-h-screen"><PublicHeader/><main className="page-wrap py-6"><section className="customs-workspace mx-auto" style={{maxWidth:640}}><CustomsStyles/><div className="customs-card" style={{gap:20,padding:'clamp(18px,4vw,28px)'}}><header><h1 className="text-2xl font-semibold">Kiểm tra / Reset key</h1><p className="mt-2 text-sm text-muted-foreground">Nhập key để xem thông tin hoặc reset thiết bị.</p></header><label>Key<Input value={key} onChange={e=>{setKey(e.target.value);setResult(null);setError('');}} placeholder="Nhập key muốn reset" autoCapitalize="characters" autoComplete="off" disabled={busy}/></label><div className="customs-actions"><Button disabled={busy||!key.trim()} onClick={()=>run('info')}>Kiểm tra key</Button><Button variant="outline" disabled={busy||!key.trim()||!runtime||(requires&&(!token||!runtime.configured))||result?.public_reset_disabled===true||result?.reset_enabled===false||['expired','blocked','refunded','deleted'].includes(result?.status)} onClick={()=>run('reset')}>{busy?'Đang xử lý…':'Reset key'}</Button></div>{requires&&siteKey&&<TurnstileWidget key={captcha} siteKey={siteKey} onTokenChange={onToken}/>}<p className="text-xs text-muted-foreground">Reset không bắt đầu lại thời hạn của key.</p>{runtimeError&&<p role="alert" className="text-sm text-destructive">{runtimeError}</p>}{requires&&runtime?.configured===false&&<p role="alert" className="text-sm text-destructive">Dịch vụ xác minh chưa được cấu hình.</p>}{requires&&runtime&&!siteKey&&<p role="alert" className="text-sm text-destructive">Chưa đọc được cấu hình widget xác minh.</p>}{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}{result&&<><h2 className="font-semibold">{result.resetDone?'Reset thành công':'Thông tin key'}</h2><KeyInformation data={result}/></>}</div></section></main></div>;
}
